nowcommunity/nowdatabase

frontend/src/App.tsx, frontend/src/components/Species/SpeciesDetails.tsx, frontend/src/components/Species/Tabs/DietTab.tsx, frontend/src/components/Species/Tabs/LocomotionTab.tsx, frontend/src/components/Species/Tabs/SizeTab.tsx, frontend/src/components/Species/Tabs/TaxonomyTab.tsx, frontend/src/components/Species/Tabs/TeethTab.tsx, frontend/src/redux/referenceReducer.ts, frontend/src/redux/speciesReducer.ts
The first version of Tabs which have no relation to other database tables.
- The Teeth tab breaks when I tried to fit the fields into four columns (maybe I coded it wrong).
- The drop downs needs to have both display and data values. Now it is only possible to code the data values.
-
=> Tabs: Taxonomy, Diet, Locomotion, Size and Teeth

backend/src/index.ts, backend/src/routes/person.ts, backend/src/routes/user.ts, backend/src/services/person.ts, backend/src/services/user.ts, frontend/src/App.tsx, frontend/src/backendTypes.d.ts, frontend/src/components/Locality/LocalityDetails.tsx, frontend/src/components/Locality/Tabs/AgeTab.tsx, frontend/src/components/Locality/Tabs/EcometricsTab.tsx, frontend/src/components/Locality/Tabs/SpeciesTab.tsx, frontend/src/components/NavBar.tsx, frontend/src/components/Person/PersonDetails.tsx, frontend/src/components/Person/PersonTable.tsx, frontend/src/components/Person/Tabs/PersonTab.tsx, frontend/src/components/Species/Tabs/DietTab.tsx, frontend/src/components/Species/Tabs/LocalitySpeciesTab.tsx, frontend/src/components/Species/Tabs/LocomotionTab.tsx, frontend/src/components/Species/Tabs/SizeTab.tsx, frontend/src/components/Species/Tabs/SynonymTab.tsx, frontend/src/components/Species/Tabs/TeethTab.tsx, frontend/src/components/User/Tabs/UserTab.tsx, frontend/src/components/User/UserDetails.tsx, frontend/src/components/User/UserTable.tsx, frontend/src/components/pages.tsx, frontend/src/redux/personReducer.ts, frontend/src/redux/userReducer.ts
I made many updates to the dropdowns.
Also, pages Person and User entities were added.
=> Week 24 kari

frontend/src/components/TableView/TableView.tsx
Small change to add borders for table data.
Check discord/yleinen for screenshot of changes
=> Borders for tables

backend/src/app.ts, backend/src/routes/crossSearch.ts, frontend/src/App.tsx, frontend/src/backendTypes.d.ts, frontend/src/components/CrossSearch/CrossSearchDetails.tsx, frontend/src/components/CrossSearch/CrossSearchTable.tsx, frontend/src/components/CrossSearch/Tabs/AgeTab.tsx, frontend/src/components/CrossSearch/Tabs/ArchaeologyTab.tsx, frontend/src/components/CrossSearch/Tabs/ClimateTab.tsx, frontend/src/components/CrossSearch/Tabs/EcometricsTab.tsx, frontend/src/components/CrossSearch/Tabs/LithologyTab.tsx, frontend/src/components/CrossSearch/Tabs/LocalityTab.tsx, frontend/src/components/CrossSearch/Tabs/MuseumTab.tsx, frontend/src/components/CrossSearch/Tabs/ProjectTab.tsx, frontend/src/components/CrossSearch/Tabs/SpeciesTab.tsx, frontend/src/components/CrossSearch/Tabs/TaphonomyTab.tsx, frontend/src/components/NavBar.tsx, frontend/src/components/pages.tsx, frontend/src/redux/api.ts, frontend/src/redux/crossSearchReducer.ts
I copied localities table view as a new view to start editing it towards a cross search functionality
=> Cross search dev

cypress/e2e/asAdmin.cy.js, frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/components/MapPage.tsx, frontend/src/components/NavBar.tsx, package-lock.json, package.json
=> Add map page

frontend/src/components/DetailView/common/tabLayoutHelpers.tsx
quick fix for detail tables to be easier to read
=> Add simple grid for detail tables

README.md
updated the test section in readme, because `npm test` doesn't do anything
=> update tests section in readme

frontend/src/components/EmailPage.tsx, frontend/src/components/FrontPage.tsx, frontend/src/components/Locality/LocalityDetails.tsx, frontend/src/components/Login.tsx, frontend/src/components/MapPage.tsx, frontend/src/components/Person/PersonDetails.tsx, frontend/src/components/Project/ProjectDetails.tsx, frontend/src/components/Reference/ReferenceDetails.tsx, frontend/src/components/Region/RegionDetails.tsx, frontend/src/components/Species/SpeciesDetails.tsx, frontend/src/components/TableView/TableView.tsx, frontend/src/components/TimeBound/TimeBoundDetails.tsx, frontend/src/components/TimeUnit/TimeUnitDetails.tsx
changes page title whenever user moves to a different page, to more clearly show user which page they are on and to show browser history more clearly
=> Titles for pages

frontend/src/components/Species/SpeciesDetails.tsx, frontend/src/validators/species.ts
Required fields for new species entries are now required
=> add initial validators for species-entries

documentation/contributing.md
=> improved documentation for using issues and Github Projects

backend/src/services/locality.ts, frontend/src/backendTypes.d.ts, frontend/src/components/Locality/LocalityTable.tsx
Added a bunch of columns to locality table but kept the default view unchanged
Also removed  | null from country as it is a required field anyway
=> add more hidden by default columns to locality table

backend/src/services/species.ts, frontend/src/backendTypes.d.ts, frontend/src/components/Species/SpeciesTable.tsx
Similar modifications as earlier to locality
=> Species table expansion

docker-compose.anon.yml
Editing features were not showing on frontend even when logged in as a user with permissions, this fixes that (on my machine at least)
=> add back ENABLE_WRITE build arg

backend/src/services/crossSearch.ts, cypress/e2e/ui.cy.js, frontend/src/backendTypes.d.ts, frontend/src/components/CrossSearch/CrossSearchTable.tsx
=> cross-search table expansion

backend/src/services/write/timeBound.ts
This should not affect anything else than the write handler that is used for time bounds, because the changes are in getTimeBoundWriteHandler (and not in the WriteHandler class itself)
=> changed the way timebound writehandler works to fix editing time bounds

backend/.gitignore, backend/Dockerfile, backend/babel.config.js, backend/jest-config.js, backend/package-lock.json, backend/package.json, backend/src/api-tests/crossSearch/get.test.ts, backend/src/api-tests/locality/contradictory_loc.test.ts, backend/src/api-tests/locality/create.test.ts, backend/src/api-tests/locality/delete.test.ts, backend/src/api-tests/locality/update.test.ts, backend/src/api-tests/species/create.test.ts, backend/src/api-tests/species/delete.test.ts, backend/src/api-tests/species/update.test.ts, backend/src/api-tests/timeBound/create.test.ts, backend/src/api-tests/timeUnit/create.test.ts, backend/src/api-tests/utils.ts, backend/src/utils/config.ts, docker-compose.test.yml, package-lock.json, package.json
Checks for coverage levels and such will come later. At this point this is only the MVP of coverage implementation.
=> Coverage for backend.

backend/src/api-tests/species/create.test.ts, backend/src/routes/species.ts, cypress/e2e/species.cy.js, frontend/src/backendTypes.d.ts, frontend/src/components/Species/SpeciesDetails.tsx
Got validation errors included in the error response along with just the status code.
Also added error handling to frontend for validation errors and tests that work with this
=> better error handling, error responses and tests

frontend/src/common.tsx
[#145](https://github.com/nowcommunity/nowdatabase/issues/145)
done
=> reference table year filter is now numeric

documentation/put_requests_for_db_entries.md
This will make more sense after #304 is merged
=> initial documentation for create and edit entries via user interface

frontend/src/components/DetailView/common/editingComponents.tsx
With this validators added for dropdown and table selector input fields also display as errors on the frontend
=> Add validator error text under dropdown and table selector input fields

backend/src/api-tests/locality/create.test.ts, backend/src/api-tests/locality/data.ts, backend/src/services/write/locality.ts, backend/src/services/write/writeOperations/utils.ts
=> add git add '!!' to the booleans that the db doesn't want to be null

frontend/src/validators/locality.ts
=> Require the respective basis for age fields when selected dating method is Absolute or Time unit

backend/src/api-tests/timeBound/create.test.ts, backend/src/api-tests/timeBound/update.test.ts, backend/src/routes/timeBound.ts, cypress/e2e/timeBound.cy.js, frontend/src/components/TimeBound/TimeBoundDetails.tsx
fixed the navigation problem, had to recreate pull request because of git issues
=> better notifications when failing to edit time bound

backend/src/api-tests/crossSearch/get.test.ts, backend/src/api-tests/locality/contradictory_loc.test.ts, backend/src/api-tests/locality/create.test.ts, backend/src/api-tests/locality/delete.test.ts, backend/src/api-tests/locality/update.test.ts, backend/src/api-tests/species/create.test.ts, backend/src/api-tests/species/delete.test.ts, backend/src/api-tests/species/update.test.ts, backend/src/api-tests/timeBound/create.test.ts, backend/src/api-tests/timeBound/update.test.ts, backend/src/api-tests/timeUnit/create.test.ts, backend/src/api-tests/timeUnit/update.test.ts, backend/src/api-tests/utils.ts
Also moved timout to imported constant in the utils file for ease of changing. 10 seconds was not long enough for my machine 😅
=> Increase test db reset timeout

cypress/e2e/locality.cy.js, frontend/src/components/Locality/Tabs/LocalityTab.tsx, frontend/src/components/Map/Map.tsx, frontend/src/components/Map/README.md, frontend/src/components/MapPage.tsx
no tests or docs yet, and ts errors most likely
=> Map select locality

backend/src/api-tests/locality/data.ts, backend/src/services/write/writeOperations/utils.ts, frontend/src/components/DetailView/Context/DetailContext.tsx, frontend/src/components/DetailView/DetailView.tsx, frontend/src/components/DetailView/common/editingComponents.tsx, frontend/src/components/Locality/Tabs/ArchaeologyTab.tsx
Also changed DropDownSelector to use empty string as value if it has no other data, to prevent errors in console.
=> radio selector buttons now always have default values

backend/src/utils/ageCalculator.ts
Simplest version of locality age calculator for time unit dating method
=> Age fraction calculator

frontend/src/components/DetailView/DetailView.tsx, frontend/src/components/DetailView/components.tsx, frontend/src/components/TimeUnit/TimeUnitDetails.tsx
This updates the up bound a low bound information boxes in frontend, so it doesn't look like the information was saved
=> onWrite function now clears editData if edit fails

backend/src/api-tests/species/create.test.ts, backend/src/api-tests/utils.ts
Implemented permission tests of #251. Others were already implemented.
=> Species tests

backend/src/api-tests/locality/update.test.ts, backend/src/routes/locality.ts, backend/src/services/locality.ts, backend/src/services/write/locality.ts
=> Locality edit error

backend/src/api-tests/species/delete.test.ts, backend/src/services/write/species.ts
=> Delete species internal server error

frontend/src/components/Species/SpeciesDetails.tsx
Last piece of species entry user story?
=> add notifycation for successful species entry

backend/src/routes/timeBound.ts, backend/src/services/timeUnit.ts, cypress/e2e/locality.cy.js, frontend/src/backendTypes.d.ts, frontend/src/components/Locality/LocalityDetails.tsx, frontend/src/components/Species/SpeciesDetails.tsx, frontend/src/components/TimeBound/TimeBoundDetails.tsx, frontend/src/components/TimeUnit/TimeUnitDetails.tsx
also refactor frontend errorhandling and modify tests to support this
=> add error norification for cascade errors and separate them from validation errors

backend/src/api-tests/reference/create.test.ts, backend/src/routes/reference.ts, backend/src/services/reference.ts, backend/src/services/write/author.ts, backend/src/services/write/journal.ts, backend/src/services/write/reference.ts, frontend/src/backendTypes.d.ts, frontend/src/components/DetailView/common/EditableTable.tsx, frontend/src/components/Reference/ReferenceDetails.tsx, frontend/src/components/Reference/Tabs/AuthorTab.tsx, frontend/src/components/Reference/Tabs/JournalTab.tsx, frontend/src/redux/referenceReducer.ts
=> Fixed a bug with wrong rows being edited in reference author fields

cypress/e2e/locality.cy.js, frontend/src/components/DetailView/Context/DetailContext.tsx, frontend/src/components/DetailView/DetailView.tsx, frontend/src/components/DetailView/common/editingComponents.tsx, frontend/src/components/Locality/Tabs/AgeTab.tsx
=> Clear age fields on timing method change

frontend/src/components/DetailView/DetailView.tsx, frontend/src/components/DetailView/common/editingComponents.tsx, frontend/src/components/Locality/Tabs/LocalityTab.tsx
Refactored to get rid of unnecessary useEffect. There is still some repetition that could be improved upon, but this is much better than previously.
=> Refactor coordinate conversion

backend/src/api-tests/reference/create.test.ts, backend/src/api-tests/reference/data.ts, backend/src/api-tests/reference/delete.test.ts, backend/src/routes/reference.ts, backend/src/services/reference.ts
=> api tests for reference, removed some unused code

cypress/e2e/locality.cy.js, frontend/src/components/Locality/Tabs/LocalityTab.tsx
Fixes regression caused by #454
=> Convert coordinates from map to dms

frontend/src/components/Locality/Tabs/LocalityTab.tsx
dec_long field was accidentally written as dec_lat, fixed and refactored while at it
=> Refactor and fix coordinate conversion handlers

cypress/e2e/locality.cy.js
should hopefully not break anything
=> major changes to locality tests

frontend/src/components/DetailView/common/editingComponents.tsx, frontend/src/components/TimeUnit/Tabs/TimeUnitTab.tsx
The time unit editing view should be a little bit easier to use now.
=> Improve time unit edit view

frontend/src/components/DetailView/components.tsx
also minor cosmetic improvements
=> fix issue with unique keys in error list

backend/src/api-tests/geonames-api.test.ts, backend/src/api-tests/geonames-api/data.ts, backend/src/routes/geonames-api.ts, frontend/src/backendTypes.d.ts, frontend/src/components/Map/CoordinateSelectionMap.tsx, frontend/src/redux/api.ts, frontend/src/redux/geonamesReducer.ts
=> Move GeoNames API call from frontend to backend

documentation/entities/reference_types.md, frontend/src/validators/reference.ts
=> Fix title requirements for journal and book references

documentation/frontend/components/TableView.md
=> Add docs for column filter mode menu

backend/src/api-tests/person/data.ts, backend/src/api-tests/person/update.test.ts, backend/src/routes/person.ts, backend/src/services/person.ts, backend/src/services/write/person.ts, frontend/src/shared/validators/person.ts
The route has the same kind of user rights checking as the get route.
The route should also deny attempts at creating a new person, this feature will happen in another pr if necessary.
=> Backend functionality for editing persons

backend/src/routes/reference.ts, backend/src/services/reference.ts, frontend/src/components/DetailView/common/SimpleTable.tsx, frontend/src/components/DetailView/common/defaultValues.ts, frontend/src/components/Reference/ReferenceDetails.tsx, frontend/src/components/Reference/Tabs/LocalityTab.tsx, frontend/src/components/Reference/Tabs/SpeciesTab.tsx, frontend/src/components/TableView/TableView.tsx, frontend/src/redux/referenceReducer.ts
The SimpleTable component on a Tab could also have pagination. At least I wasn't able to add one. If you know how to do it, please add. See, for example, Reference 23438, which lists a lot of Localities and Species that are related to this reference.
Resolves #395
=> New tabs to reference

backend/src/api-tests/user/login.test.ts, backend/src/routes/user.ts, cypress/e2e/login.cy.js, cypress/e2e/person.cy.js, cypress/e2e/userPage.cy.js, frontend/src/components/Person/PersonDetails.tsx, frontend/src/components/Person/Tabs/ChangePasswordForm.tsx, frontend/src/components/Person/Tabs/PersonTab.tsx, frontend/src/components/pages.tsx, frontend/src/redux/api.ts, frontend/src/redux/personReducer.ts
I also added a redirect from `/person/<initials>` to `/person/user-page` if the user does not have the admin role. This is to simplify things since every user type should be able to access their user page, while only admins should be able to access other people's details.
=> Frontend functionality for editing persons

cypress/e2e/timeUnit.cy.js, frontend/src/components/DetailView/common/checkFieldErrors.tsx, frontend/src/components/DetailView/common/editingComponents.tsx, frontend/src/components/TimeUnit/Tabs/TimeUnitTab.tsx
This should be a bit more clear for the user.
=> Bug fix in editingComponents error checking function, and changed the way time bounds are displayed/selected in time unit view

frontend/src/components/Species/Tabs/TeethTab.tsx, frontend/src/components/pages.tsx
=> Time unit page caption
