- backend/prisma/schema.prisma
- backend/src/services/species.ts
- frontend/src/backendTypes.d.ts
- frontend/src/components/Species/SpeciesDetails.tsx
- frontend/src/components/Species/Tabs/LocalitySpeciesTab.tsx
- frontend/src/components/Species/Tabs/LocalityTab.tsx
- frontend/src/components/Species/Tabs/SynonymTab.tsx
- frontend/src/components/Species/Tabs/UpdateTab.tsx
I added new Tabs for Species.
I added all fields to show the long list in the Locality-Species Information.
We should think of some solution for those kinds of lists later.
On the same Tab, the edits need to be managed like in the PHP NOW (in-line edits on a list). Or the edit could be done by opening the current row for edit mode.
I need to modify the current edit as it now works in a similar way as the Locality tab.
> Species table new tabs

- backend/package-lock.json
- backend/package.json
Typescript failed to build backend because jest types were missing.
> installed jest types for typescript

- backend/src/routes/crossSearch.ts
- backend/src/services/crossSearch.ts
- frontend/src/components/CrossSearch/CrossSearchTable.tsx
- frontend/src/redux/crossSearchReducer.ts
Did a small patch of cleanup. Removed code I had copypasted from locality view. I figured that the csv-table for cross-search does not need a special export. The export table -button prints a nice clean .csv
> Cross search cleanup

- frontend/src/components/DetailView/DetailBrowser.tsx
- frontend/src/components/DetailView/DetailView.tsx
- frontend/src/components/pages.tsx
Increased the font-size. I'm not entirely happy how it positions it differently depending on where in the list is it and also too long names just fade out, but neither of these might be real problems.
> increase the font of name of headers in detail views

- backend/package.json
- backend/src/api-tests/crossSearch/get.test.ts
- backend/src/api-tests/locality/contradictory_loc.test.ts
- backend/src/api-tests/locality/create.test.ts
- backend/src/api-tests/locality/delete.test.ts
- backend/src/api-tests/species/create.test.ts
- backend/src/api-tests/species/delete.test.ts
- backend/src/api-tests/species/update.test.ts
- backend/src/api-tests/timeBound/create.test.ts
- backend/src/api-tests/timeUnit/create.test.ts
- backend/src/api-tests/utils.ts
- backend/src/routes/test.ts
- backend/src/utils/db.ts
- docker-compose.anon.yml
- docker-compose.dev.yml
- docker-compose.test.yml
Api-tests now reset the database utilizing jest's `beforeAll`.
> Api tests db reset

- backend/src/api-tests/species/create.test.ts
- backend/src/api-tests/species/data.ts
- backend/src/api-tests/species/update.test.ts
- backend/src/routes/species.ts
- backend/src/services/species.ts
- cypress/e2e/species.cy.js
- frontend/src/components/Species/SpeciesDetails.tsx
This time working I hope.
Had to switch 'id' to 'species_id' in back end responses to work with current frontend and not touching backendtypes. Also some twiddling with some frontend logic to mimic localitys front end logic. Also needed to add a 15ms time-out to navigation to '/species/<new-species-id>'. I don't think this is the best way to do this, but without it it rendered the wrong view approx 50% of the time when submitting a valid species entry. These entries are inserted to database correctly anyway, but a view for a new, empty species was rendered. So I guess the code tried to call navigate(`/species/${species_id}`) before species_id was defined and did not complete the navigation and returned to '/species/new'.
Another thing is that if the backend raises validation errors, atm …
> Species validators v2

- backend/src/api-tests/timeUnit/create.test.ts
- backend/src/routes/timeUnit.ts
- frontend/src/components/TimeUnit/TimeUnitDetails.tsx
had to add the ugly type check in the onWrite() function, because it has to differentiate between a validationError and an internal server error (because changing time unit name does not work atm).
> notification now tells which fields are missing

- frontend/src/components/DetailView/common/editingComponents.tsx
- frontend/src/components/TimeUnit/Tabs/TimeUnitTab.tsx
- frontend/src/validators/timeUnit.ts
- frontend/src/validators/validator.ts
Added a new editingComponent dedicated to Time bound selection, because I don't know how to get this to work otherwise. Also added a new optional function to validators to run any function you want to when validating
> Fix time unit validator issue

- frontend/src/components/DetailView/common/editingComponents.tsx
- frontend/src/components/DetailView/common/tabLayoutHelpers.tsx
- frontend/src/components/TimeBound/TimeBoundTable.tsx
- frontend/src/components/TimeUnit/Tabs/TimeUnitTab.tsx
When editing time unit, added a small border to time bound that has been changed so it's easier for the user to see. Also renamed "New Upper Bound" to "New Upper Bound Id" (same for lower bound), and the TableView that opens when the user is selecting a new time bound now shows ids by default.
> Make time unit editing more intuitive

- frontend/src/components/DetailView/common/editingComponents.tsx
Changed this because otherwise giving the RadioSelector a default value would not update the data
> radio selector now adds its defaultValue to editData

- frontend/src/components/CrossSearch/CrossSearchTable.tsx
- frontend/src/components/Locality/LocalityTable.tsx
When initially implementing these columns, I did not realize they were text columns.
> Remove range from text filter

- cypress/e2e/timeUnit.cy.js
- frontend/src/components/TimeUnit/Tabs/TimeUnitTab.tsx
Because time unit names cannot currently be edited (and making them editable is a big task), the field is now disabled.
> disable time unit name field

- backend/src/api-tests/timeUnit/update.test.ts
- backend/src/routes/timeUnit.ts
- backend/src/services/write/locality.ts
- backend/src/services/write/species.ts
- backend/src/services/write/timeUnit.ts
- backend/src/services/write/writeOperations/writeHandler.ts
- backend/src/utils/cascadeHandler.ts
- backend/src/utils/db.ts
- cypress/e2e/timeUnit.cy.js
Cascading effects of time units are now checked and edits don't go through if contradicting localities would emerge.
These are only checked, if time unit itself is valid and cascading errors are separated from validation errors.
Notifying errors correctly will be in another task
> add initial functionality for timeunit cascades

- backend/src/api-tests/timeBound/update.test.ts
- backend/src/routes/timeBound.ts
- backend/src/routes/timeUnit.ts
- backend/src/services/write/timeBound.ts
- backend/src/services/write/timeUnit.ts
- backend/src/utils/cascadeHandler.ts
- cypress/e2e/timeBound.cy.js
- frontend/src/components/TimeBound/TimeBoundDetails.tsx
Editing timebounds checks if it would break time units or localities before making changes. If something would break, changes are cancelled and user is informed. If nothing would break, all entities are updated. Time units are not yet logged
Updated tests to manage the changes and added 1 api-test for breaking timeunit when editing time bound
> Timebound cascade effects

- backend/src/api-tests/reference/create.test.ts
- backend/src/services/write/reference.ts
- backend/src/services/write/writeOperations/utils.ts
- documentation/entities/reference_types.md
- frontend/src/components/DetailView/DetailView.tsx
- frontend/src/components/DetailView/common/editingComponents.tsx
- frontend/src/components/Locality/Tabs/LocalityTab.tsx
- frontend/src/components/Reference/Tabs/ReferenceTab.tsx
- frontend/src/validators/reference.ts
- frontend/src/validators/validator.ts
And some changes to handle dates in different components
> more validators for references, date selection for references

- docker-compose.anon.yml
- docker-compose.dev.yml
phpMyAdmin seemed like the better option as adminer has not been maintained for 2 years. There is a fork `adminerevo` but PMA feels like the more "stable" option at the moment.
> added phpmyadmin to docker compose of dev environments

- frontend/src/components/Notification.tsx
- frontend/src/components/TimeBound/TimeBoundDetails.tsx
- frontend/src/components/TimeUnit/TimeUnitDetails.tsx
also changed the cascadeError/calculateError messages to not close automatically.
> add optional custom timeout value to notifications

- frontend/src/components/DetailView/DetailBrowser.tsx
- frontend/src/components/Page.tsx
- frontend/src/components/pages.tsx
Done:
- headers for locality, species
- headers for references (not perfect but seemed ok)
TODO
- other headers
- docs?
- tests?
> New headers

- frontend/src/components/Person/PersonTable.tsx
There are two columns with the same accessorKey and thus the same id in PersonTable. This caused a lot of error messages and weird things to happen when showing/hiding columns, so I added an additional id value to one of them.
> fix id error in person table

- backend/src/services/write/region.ts
- cypress/e2e/region.cy.js
- frontend/src/components/Region/RegionDetails.tsx
- frontend/src/components/Region/Tabs/CoordinatorTab.tsx
- frontend/src/shared/types/data.ts
- frontend/src/shared/validators/region.ts
I made a new type called `RegionDetailsWithComPeople` that is used in Region's CoordinatorTab to allow adding the com_people field to the editData manually in the SelectingTables. Not sure if this is the best way to deal with the issue.
This PR also doesn't have anything related to creating new regions, I will look at that later.
> Frontend editing functionality for regions

- backend/package-lock.json
- backend/package.json
- backend/src/app.ts
- backend/src/routes/email.ts
- documentation/backend/rate_limiting_for_emails.md
- frontend/src/components/DetailView/common/ContactForm.tsx
Also modified the contact form notification to show user when the limit is reached.
Currently the limiter is defined inside app.ts, I'm not sure if it should be there or inside the email.ts route file but I chose this for now.
The limiter should allow one email every 15 seconds, per user. However, this should be tested in production since getting the IP address of users might work differently there compared to local testing.
> add express-rate-limit for email rate limiting

- documentation/devops/commands.md
Because I took ages to figure out that `--volumes` exists.
> modified docker docs slightly

- backend/src/services/species.ts
Species with `ref_ref.exact_date = NULL`
> Fixed bug where locality details query breaks on certain species
